### ISSUE TITLE
Puertos expuestos

### ISSUE THREAD

**Issue by aboglioli** [andes/andes-docker#2]
Los puertos expuestos a través de `ports` no sólo quedan expuestos para el entorno local sino que para el exterior también ya que Docker sobreescribe iptables de Linux, es decir, no se pueden bloquear con un firewall. En algunos casos utilizando un firewall como `ufw` puede dar problemas.

```
 andes_db:  
  image: mongo:3.4
  container_name: andes_db
  volumes:
    - vandes:/data/db
  ports:
    - "27017:27017" 
```
En este caso, la base de datos quedaría expuesta al exterior.

He experimentado este problema antes utilizando la versión 3 del archivo de `docker-compose.yml`. Habría que evaluar si sucede lo mismo con la versión 2. No encontré nada en la documentación oficial.

No es recomendable hacer esto ya que `docker-compose` crea una red para todos los contenedores en donde se pueden ver sin necesidad de exponer puertos.

Para tener en cuenta: [https://fralef.me/docker-and-iptables.html](https://fralef.me/docker-and-iptables.html)

Cuando tenga un tiempo lo pruebo.
